# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Seed configurations

version: 2

seeds:

  - name: site_timezones
    description: Mapping from site in meta.sourceIdentifier.system to timezone for that site.
    columns:
      - name: site
        description: Name of site as stored in meta.sourceIdentifier.system.
      - name: bq_timezone
        description: BigQuery-valid timezone, see [list of valid tz database entries](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

  - name: clinical_code_groups
    description: Reference table mapping clinical codes to broader clinical groups.
    columns:
      - name: group_type
        description: Clinical category that this group belongs to (e.g. Condition, Procedure, Observation).
      - name: group
        description: Name of the clinical group.
      - name: code
        description: Clinical code that is mapped to the clinical group.
      - name: display
        description: Display name for the clinical code.
      - name: system
        description: Coding system from which this clinical code is defined (e.g. http://snomed.info/sct).
    config:
      column_types: {
        group_type: string,
        group: string,
        code: string,
        display: string,
        system: string
      }

  - name: thresholds
    description: Metric thresholds.
    columns:
      - name: metric_name
        description: Name of metric
      - name: threshold_low
        description: The lowest value that the measure can take and pass this validation test
      - name: threshold_high
        description: The highest value that the measure can take and pass this validation test
      - name: time_grain
        description: Optional date grain (YEAR, MONTH, WEEK, QUARTER, DAY). Blank => Whole time period
      - name: dimension
        description: Metric dimension (a, b or c). Leave blank to set thresholds for the metric calculated at the overall level without segmenting by dimensions.
      - name: validation_feature
        description: E.g Care Studio Notes
      - name: severity
        description: Error, Warn
    # TODO: add tests here to make sure that users format this file correctly.
    # - Make sure no duplicate rows
    # - Make sure grain, dimension, severity fields only contain allowed values
    #- Make sure metric_name all exist in metric_definitions.
    config:
      column_types: {
        metric_name: string,
        threshold_low: decimal,
        threshold_high: decimal,
        time_grain: string,
        dimension: string,
        validation_feature: string,
        severity: string
      }
